<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="QA-SWAMYK" name="com.quotetoorder.acorn.Duplicate_Quote" tests="6" failures="1" timestamp="2021-02-05T10:40:16 IST" time="355.070" errors="0">
  <testcase name="testOECAccount" time="47.928" classname="com.quotetoorder.acorn.Duplicate_Quote"/>
  <system-out/>
  <testcase name="testNAVtoCPQ" time="65.338" classname="com.quotetoorder.acorn.Duplicate_Quote"/>
  <system-out/>
  <testcase name="testTransactionDetails" time="87.539" classname="com.quotetoorder.acorn.Duplicate_Quote"/>
  <system-out/>
  <testcase name="testCalculateChargesTab" time="39.542" classname="com.quotetoorder.acorn.Duplicate_Quote">
    <failure type="java.lang.AssertionError" message="expected [$13.71] but found [$6.85]">
      <![CDATA[java.lang.AssertionError: expected [$13.71] but found [$6.85]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.quotetoorder.acorn.Duplicate_Quote.testCalculateChargesTab(Duplicate_Quote.java:176)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testCalculateChargesTab -->
  <system-out/>
  <testcase name="testApprovalsTab" time="55.925" classname="com.quotetoorder.acorn.Duplicate_Quote"/>
  <system-out/>
  <testcase name="testReturnCPQToOEC" time="58.798" classname="com.quotetoorder.acorn.Duplicate_Quote"/>
  <system-out/>
</testsuite> <!-- com.quotetoorder.acorn.Duplicate_Quote -->
